/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.exercise

class TrivialSpec : StringSpec() {
    init {
        "Should be successful" {
            2 + 2 shouldBe 4
        }
    }

}
